---
- name: clone sidewinderd
  git:
    repo: https://github.com/tolga9009/sidewinderd.git
    dest: "{{ setupDir }}/sidewinderd"
    update: no

- name: set sidewinderd file permissions
  file:
    dest: "{{ setupDir }}/sidewinderd"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    recurse: yes

- name: install required dependencies
  dnf:
    name:
    - cmake
    - libconfig-devel
    - tinyxml2-devel
    - systemd-devel
    - g++
    state: present

- name: create build directory
  file:
    path: "{{ setupDir }}/sidewinderd/build"
    owner: '{{ user }}'
    group: '{{ user }}'
    state: directory

- name: cmake sidewinderd
  command: cmake ..
  become: yes
  become_user: '{{ user }}'
  args:
    chdir: "{{ setupDir }}/sidewinderd/build"
    creates: "{{ setupDir }}/sidewinderd/build/Makefile"

- name: make sidewinderd
  command: make
  become: yes
  become_user: '{{ user }}'
  args:
    chdir: "{{ setupDir }}/sidewinderd/build"
    creates: "{{ setupDir }}/sidewinderd/build/src/sidewinderd"

- name: make install sidewinderd
  command: make install
  args:
    chdir: "{{ setupDir }}/sidewinderd/build"
    creates: /usr/local/bin/sidewinderd

- name: configure sidewinderd
  template:
    src: sidewinderd.conf.j2
    dest: /etc/sidewinderd.conf
    owner: root
    group: root
    mode: '0644'

- name: start sidewinderd
  service:
    name: sidewinderd
    enabled: yes
    state: started
