- name: Remove Fedora ffmpeg-free package to avoid RPM Fusion conflict
  dnf:
    name: ffmpeg-free
    state: absent

- name: Install multimedia packages
  dnf:
    name:
      - ffmpeg
      - audacity
      - strawberry
      - vlc
      - gimp
    state: present
    allowerasing: yes

- name: Install spotify
  dnf:
    name:
      - lpf-spotify-client
    state: present
    disable_excludes: all
    
