# Master playbook for Fedora workstation setup

---
- name: Fedora workstation automated setup
  hosts: localhost

  vars_prompt:
    - name: user
      prompt: "Enter linux user you want to configure for"
      private: no
  pre_tasks:
    - name: setup tmpdir
      file:
        path: '{{ tmpdir }}'
        state: directory
        recurse: yes
    - name: set hostname
      hostname:
        name: '{{ hostname }}'
  roles:
    - role: base
      tags:
        - base 
    - role: browsers
      tags:
        - browsers
    - role: development
      tags:
        - development
    - role: discord
      tags:
        - discord
    - role: download_tools
      tags:
        - download
        - tools
    - role: gnome
      tags:
        - gnome
    - role: multimedia
      tags:
        - multimedia
    - role: networking
      tags:
        - networking
    - role: storage_tools
      tags:
        - storage_tools
        - tools
    - role: nvidia
      tags:
        - nvidia
    - role: unity
      tags:
        - unity
    - role: virtualization
      tags:
        - virtualization
    - role: 3d_modelling
      tags:
        - 3d_modelling
    - role: games
      tags:
        - games
    - role: cryptomator
      tags:
        - cryptomator
    - role: syncthing
      tags:
        - syncthing
    - role: sidewinderd
      tags:
        - sidewinderd
    - role: grub
      tags:
        - grub