- name: Install common development tools
  dnf:
    name:
      - python3-devel
      - maven
      - java-latest-openjdk-devel
    state: present

- name: Import vscode
  import_tasks: vscode.yml
  tags:
    - vscode

- name: Import go
  import_tasks: go.yml
  tags:
    - go

- name: Import nvm
  import_tasks: nvm.yml
  tags:
    - nvm

- name: Import mono
  import_tasks: mono.yml
  tags:
    - mono