---
- name: download cryptomator
  get_url:
    url: "https://github.com/cryptomator/cryptomator/releases/download/1.15.1/cryptomator-1.15.1-x86_64.AppImage"
    dest: '/home/{{ user }}/Desktop/Cryptomator.AppImage'
    checksum: sha256:0873ed665202493e3b00ecdb8ec9fd2d5b5d318089fb5cf048c045278772e3ba
    mode: 0555
    owner: '{{ user }}'
    group: '{{ user }}'
