---
- name: download cryptomator
  become: yes
  become_user: "{{ user }}"
  get_url:
    url: https://github.com/cryptomator/cryptomator/releases/download/1.5.17/cryptomator-1.5.17-x86_64.AppImage
    dest: '/home/{{ user }}/Desktop/Cryptomator.AppImage'
    checksum: sha256:1b662a3746c266beb8444e529541d1712e6e3f5807229231083663535ac530f8
    mode: 0555
