keybind_path: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings'
gnome_dconf_values:
  # Desktop keybindings
  - { key: "/org/gnome/desktop/wm/keybindings/show-desktop", value: "['<Super>d']", state: "present" }

  # Media keys
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/calculator", value: "['<Super>c']", state: "present" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/home", value: "['<Super>e']", state: "present" }

custom_keybindings:
  - { name: "terminal", command: "gnome-terminal", binding: "<Control><Alt>t" }
  - { name: "cryptomator", command: "~/Desktop/Cryptomator.App", binding: "<Super>k" }
  - { name: "unityhub", command: "unityhub", binding: "<Super>u" }