- name: Install virtualization packages
  dnf:
    name:
    - qemu
    - qemu-img
    - '@Virtualization'
    state: present

- name: Import docker
  import_tasks: docker.yml
  tags:
    - docker

- name: Import passthrough
  import_tasks: passthrough.yml
  tags:
    - passthrough