- name: git clone passthrough_helper_fedora
  git:
    repo: https://github.com/pavolelsig/passthrough_helper_fedora.git
    dest: "{{ setupDir }}/passthrough_helper_fedora"
    update: no

- name: git clone IOMMU viewer
  git:
    repo: https://github.com/pavolelsig/IOMMU-viewer.git
    dest: "{{ setupDir }}/IOMMU-viewer"
    update: no

- name: git clone Scream helper
  git:
    repo: https://github.com/pavolelsig/Scream_helper.git
    dest: "{{ setupDir }}/Scream_helper"
    update: no

- name: git clone Scream
  git:
    repo: https://github.com/duncanthrax/scream.git
    dest: "{{ setupDir }}/Scream_helper/scream-master"
    update: no

- name: git clone vfio-pci-bind
  git:
    repo: https://github.com/andre-richter/vfio-pci-bind.git
    dest: "{{ setupDir }}/vfio-pci-bind"
    update: no

- name: download virtio iso
  get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.185-2/virtio-win-0.1.185.iso
    dest: "{{ setupDir }}/virtio-win-0.1.185.iso"
    checksum: sha256:af2b3cc9fa7905dea5e58d31508d75bba717c2b0d5553962658a47aebc9cc386

- name: find all scripts in setup folder
  find:
    paths:
    - "{{ setupDir }}/passthrough_helper_fedora/"
    - "{{ setupDir }}/IOMMU-viewer/"
    - "{{ setupDir }}/Scream_helper/"
    - "{{ setupDir }}/vfio-pci-bind/"
    patterns: "*.sh"
    recurse: yes
  register: output

- name: set execute privileges to all scripts
  file:
    path: "{{ item.path }}"
    mode: u+x,g+x,o+x
  with_items: "{{ output.files }}"

- name: add vfio driver config to dracut
  copy:
    src: dracut_vfio.conf
    dest: /etc/dracut.conf.d/vfio.conf
    owner: root
    group: root
    mode: '0644'

- name: add vfio driver config to modprobe
  template:
    src: modprobe_vfio.conf.j2
    dest: /etc/modprobe.d/vfio.conf
    owner: root
    group: root
    mode: '0644'
  when: vfio_pci_gpu_ids is defined

- name: Update initramfs
  command: dracut -f
  register: dracut_result
  changed_when: dracut_result.stdout != ""