---
- name: "install unity repository"
  copy:
    dest: /etc/yum.repos.d/unityhub.repo
    content: |
      [unityhub]
      name=Unity Hub
      baseurl=https://hub.unity3d.com/linux/repos/rpm/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://hub.unity3d.com/linux/repos/rpm/stable/repodata/repomd.xml.key
      repo_gpgcheck=1

- name: "install unity hub"
  dnf:
    name: unityhub
    state: present
