---
- name: create folder for syncthing
  become: yes
  become_user: "{{ user }}"
  file:
    path: '/home/{{ user }}/syncthing'
    state: directory

- name: create docker-compose file for syncthing
  become: yes
  become_user: "{{ user }}"
  copy:
    dest: '/home/{{ user }}/syncthing/docker-compose.yml'
    content: |
      version: "2.1"
      services:
        syncthing:
          image: ghcr.io/linuxserver/syncthing
          container_name: syncthing
          hostname: syncthing
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
          volumes:
            - /home/{{ user }}/syncthing/config:/config
            - /sync:/sync
          ports:
            - 127.0.0.1:8384:8384
            - 22000:22000/tcp
            - 22000:22000/udp
            #- 21027:21027/udp
          restart: unless-stopped
