---
- name: create folder for syncthing
  become: true
  become_user: "{{ user }}"
  file:
    path: '/home/{{ user }}/syncthing'
    state: directory

- name: create docker-compose file for syncthing
  become: true
  become_user: "{{ user }}"
  template:
    src: docker-compose.yml.j2
    dest: '/home/{{ user }}/syncthing/docker-compose.yml'